#:schema node_modules/wrangler/config-schema.json
name = "links"
compatibility_date = "2024-07-12"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "KV"
id = "3d2004c75314409d8fafab5f06f4b365"
